---

- name: 'Run: nginx container'
  docker_container:
    name: nginx
    hostname: nginx
    image: '{{ nginx_pkg }}'
    state: started
    restart_policy: always
    memory: '{{ container_memory_limit }}'
    volumes: '{{ nginx_container_volumes }}'
    ports: '{{ nginx_ports_mapping }}'
    networks: docker_network
