---

- name: run nginx container
  docker_container:
    name: "{{ container_name }}"
    hostname: nginx
    state: present
    image: "{{ nginx_docker_image }}:{{ nginx_docker_image_tag }}"
    ports: "{{ nginx_ports_mapping }}"
    networks:
      - name: snet
