---

- name: run nginx container
  docker_container:
    name: balancer
    hostname: nginx
    state: started
    image: "{{ nginx_docker_image }}:{{ nginx_docker_image_tag }}"
    pull: true
    ports: "{{ nginx_ports_mapping }}"
    networks:
      - name: snet
    volumes:
      - /var/locale/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
