---

- name: nginx container
  docker_container:
    name: nginx
    hostname: nginx
    image: "{{ nginx_package_name }}"
    state: started
    restart_policy: always
    memory: "{{ container_memory_limit }}"
    ports: "{{ nginx_ports_mapping }}"
    networks: 
      - name: snet
    volumes: "{{ nginx_container_volumes }}"
