---

- name: nginx container
  docker_container:
    name: balancer
    hostname: nginx
    image: "nginx:latest"
    state: started
 #   restart_policy: always
    memory: "{{ container_memory_limit }}"
    ports: "{{ nginx_ports_mapping }}"
    networks: 
      - name: snet
    volumes: "{{ nginx_container_volumes }}"
