---

- name: create directory
  file:
    src: nginx.conf.j2
    path: "/var/locale/nginx"
    state: "directory"
    mode: "0755"
  become: yes

- name: config
  template:
    src: nginx.conf.j2
    dest: /var/locale/nginx/nginx.conf
