---

- name: create directory
  become: yes
  become_method: sudo
  file:
    path: "/home/jenkins/workspace/nginx"
    state: "directory"
    mode: "0755"

- name: config
  template:
    src: nginx.conf.j2
    dest: /home/jenkins/workspace/nginx/nginx.conf
