---

- name: create directory
  file:
  become: yes
  become_method: sudo
    path: "/var/locale/nginx"
    state: "directory"
    mode: "0755"

- name: config
  template:
    src: nginx.conf.j2
    dest: /var/locale/nginx/nginx.conf
