---

- name: create directory
  become: yes
  become_method: sudo
  file:
    path: "/tmp/nginx"
    state: "directory"
    mode: "0755"

- name: config
  template:
    src: nginx.conf.j2
    dest: /tmp/nginx/nginx.conf
