---

- name: include docker
  include_role:
    name: docker-role

- import_tasks: flaskapp.yml

- import_tasks: config.yml

- import_tasks: build.yml

- name: Copy in the container
  command: docker cp /home/jenkins/workspace/nginx/nginx.conf '{{ container_name }}':/etc/nginx/nginx.conf
  become: yes
  become_method: sudo

- name: Run nginx container.
  docker_container:
    name: "{{ container_name }}"
    exposed_ports: "{{ nginx_exposed_ports }}"
    ports: "{{ nginx_ports_mapping }}"
    networks:
      - name: snet
    state: started
    restart: yes
    volumes:
      - /home/jenkins/workspace/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
