---

- name: include docker
  include_role:
    name: docker-role

- import_tasks: flaskapp.yml

- import_tasks: config.yml

- import_tasks: build.yml

- name: Copy in the container
  # From host to container
  command: docker cp /home/jenkins/workspace/nginx/nginx.conf balancer:/etc/nginx/nginx.conf
  # From container to host
  #command: docker cp balancer:/etc/nginx/nginx.conf /home/jenkins/workspace/nginx/nginx.conf
  become: yes
  become_method: sudo

- name: Nginx service restart (for alpine-nginx) 
  command: docker exec balancer bash -c 'service nginx restart'

#- name: Stop nginx container.
#  docker_container:
#    name: "{{ container_name }}"
#    state: stopped
#
#- name: Start nginx container.
#  docker_container:
#    name: "{{ container_name }}"
#    state: started
