---

- name: include docker
  include_role:
    name: docker-role

- import_tasks: flaskapp.yml

- import_tasks: config.yml

- import_tasks: build.yml

- name: Copy in the container
  command: docker cp /home/jenkins/workspace/nginx/nginx.conf '{{ container_name }}':/etc/nginx/nginx.conf
  become: yes
  become_method: sudo

- name: Run nginx container.
  docker_container:
    name: "{{ container_name }}"
    state: started
