---
- name: 'Configuration: Prepare empty volumes list'
  set_fact:
    nginx_container_volumes: []
  changed_when: false

- name: 'Configuration: Prepare mounted folders volumes list'
  set_fact:
    nginx_container_volumes: /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    with_items: '{{ nginx_mounted_folders }}'
  changed_when: nginx_mounted_folders_status.changed
